from datetime import datetime, timedelta, timezone
from decimal import Decimal
from app.schemas.shop import Product, Review

IMG = "https://images.unsplash.com"


def product_image(photo: str) -> str:
    return f"{IMG}/{photo}?auto=format&fit=crop&w=900&q=80"


PRODUCTS: list[Product] = [
    Product(
        id="auralux-pro-headphones",
        name="Auralux Pro Noise-Canceling Headphones",
        description="Wireless headphones with adaptive noise canceling, long battery life, and warm studio-grade sound.",
        price=Decimal("149.00"),
        category="Electronics",
        brand="Auralux",
        rating=4.8,
        stock=18,
        images=[product_image("photo-1505740420928-5e560c06d30e"), product_image("photo-1546435770-a3e426bf472b")],
        colors=["Graphite", "Sand", "Teal"],
        sizes=[],
        tags=["audio", "travel", "work"],
        created_at=datetime.now(timezone.utc) - timedelta(days=8),
    ),
    Product(
        id="northstar-video-laptop",
        name="Northstar Creator 14 Laptop",
        description="Portable laptop tuned for video editing with OLED display, 32GB memory, and dedicated graphics.",
        price=Decimal("1299.00"),
        category="Electronics",
        brand="Northstar",
        rating=4.7,
        stock=9,
        images=[product_image("photo-1496181133206-80ce9b88a853"), product_image("photo-1517336714731-489689fd1ca8")],
        colors=["Silver", "Midnight"],
        sizes=["1TB", "2TB"],
        tags=["laptop", "creator", "video editing"],
        created_at=datetime.now(timezone.utc) - timedelta(days=3),
    ),
    Product(
        id="vela-red-runner",
        name="Vela Red Runner Sneaker",
        description="Lightweight red running shoes with responsive foam and breathable knit for daily miles.",
        price=Decimal("49.99"),
        category="Style",
        brand="Vela",
        rating=4.4,
        stock=31,
        images=[product_image("photo-1542291026-7eec264c27ff"), product_image("photo-1549298916-b41d501d3772")],
        colors=["Red", "Black"],
        sizes=["7", "8", "9", "10", "11"],
        tags=["shoes", "running", "under 50"],
        created_at=datetime.now(timezone.utc) - timedelta(days=12),
    ),
    Product(
        id="kanso-linen-overshirt",
        name="Kanso Linen Overshirt",
        description="Soft linen overshirt that layers easily for workdays, weekend travel, and relaxed dinners.",
        price=Decimal("72.00"),
        category="Style",
        brand="Kanso",
        rating=4.5,
        stock=24,
        images=[product_image("photo-1520975682031-a5a9f3f17908"), product_image("photo-1489987707025-afc232f7ea0f")],
        colors=["Olive", "White", "Navy"],
        sizes=["XS", "S", "M", "L", "XL"],
        tags=["shirt", "linen", "capsule"],
        created_at=datetime.now(timezone.utc) - timedelta(days=22),
    ),
    Product(
        id="orbit-smartwatch-sport",
        name="Orbit Sport Health Watch",
        description="Fitness smartwatch with sleep coaching, GPS workouts, heart insights, and seven-day battery.",
        price=Decimal("199.00"),
        category="Wellness",
        brand="Orbit",
        rating=4.6,
        stock=14,
        images=[product_image("photo-1523275335684-37898b6baf30"), product_image("photo-1508685096489-7aacd43bd3b1")],
        colors=["Black", "Blue", "Cream"],
        sizes=["40mm", "44mm"],
        tags=["watch", "fitness", "health"],
        created_at=datetime.now(timezone.utc) - timedelta(days=5),
    ),
    Product(
        id="luma-desk-lamp",
        name="Luma Focus Desk Lamp",
        description="Dimmable LED desk lamp with warm/cool modes, wireless charging, and low-glare reading light.",
        price=Decimal("59.00"),
        category="Home",
        brand="Luma",
        rating=4.3,
        stock=42,
        images=[product_image("photo-1507473885765-e6ed057f782c"), product_image("photo-1513506003901-1e6a229e2d15")],
        colors=["White", "Black"],
        sizes=[],
        tags=["desk", "lamp", "office"],
        created_at=datetime.now(timezone.utc) - timedelta(days=16),
    ),
    Product(
        id="terra-ceramic-cookware",
        name="Terra Ceramic Cookware Set",
        description="Nonstick ceramic cookware bundle with even heating, comfortable handles, and easy cleanup.",
        price=Decimal("139.00"),
        category="Home",
        brand="Terra",
        rating=4.9,
        stock=11,
        images=[product_image("photo-1556911220-bff31c812dba"), product_image("photo-1584990347449-a86c2e3f0764")],
        colors=["Sage", "Slate"],
        sizes=["8 piece", "12 piece"],
        tags=["kitchen", "bundle", "gift"],
        created_at=datetime.now(timezone.utc) - timedelta(days=2),
    ),
    Product(
        id="northstar-pocket-phone",
        name="Northstar Pocket X Phone",
        description="Compact smartphone with all-day battery, sharp cameras, and AI photo cleanup built in.",
        price=Decimal("699.00"),
        category="Mobile",
        brand="Northstar",
        rating=4.5,
        stock=21,
        images=[product_image("photo-1511707171634-5f897ff02aa9"), product_image("photo-1598327105666-5b89351aff97")],
        colors=["Black", "Blue", "Rose"],
        sizes=["128GB", "256GB"],
        tags=["phone", "camera", "mobile"],
        created_at=datetime.now(timezone.utc) - timedelta(days=6),
    ),
    Product(
        id="luma-aroma-diffuser",
        name="Luma Aroma Diffuser",
        description="Quiet ceramic diffuser with soft light modes, automatic shutoff, and calm gift-ready packaging.",
        price=Decimal("39.00"),
        category="Gifts",
        brand="Luma",
        rating=4.2,
        stock=36,
        images=[product_image("photo-1608571423902-eed4a5ad8108"), product_image("photo-1602910344008-22f323cc1817")],
        colors=["White", "Stone"],
        sizes=[],
        tags=["gift", "mom", "wellness", "under 50"],
        created_at=datetime.now(timezone.utc) - timedelta(days=10),
    ),
    Product(
        id="terra-weekender-bag",
        name="Terra Weekender Carryall",
        description="Structured travel bag with laptop sleeve, shoe pocket, and weather-resistant recycled fabric.",
        price=Decimal("118.00"),
        category="Gifts",
        brand="Terra",
        rating=4.6,
        stock=16,
        images=[product_image("photo-1553062407-98eeb64c6a62"), product_image("photo-1548036328-c9fa89d128fa")],
        colors=["Forest", "Black"],
        sizes=[],
        tags=["travel", "gift", "bag"],
        created_at=datetime.now(timezone.utc) - timedelta(days=17),
    ),
    Product(
        id="auralux-sleep-buds",
        name="Auralux Sleep Buds",
        description="Low-profile earbuds with soothing sound masks and comfort tips for side sleepers.",
        price=Decimal("89.00"),
        category="Wellness",
        brand="Auralux",
        rating=4.1,
        stock=19,
        images=[product_image("photo-1590658268037-6bf12165a8df"), product_image("photo-1606220945770-b5b6c2c55bf1")],
        colors=["Mist", "Graphite"],
        sizes=["S", "M", "L"],
        tags=["sleep", "audio", "wellness"],
        created_at=datetime.now(timezone.utc) - timedelta(days=20),
    ),
    Product(
        id="orbit-yoga-kit",
        name="Orbit Yoga Starter Kit",
        description="Supportive mat, blocks, strap, and towel for home practice or studio sessions.",
        price=Decimal("64.00"),
        category="Wellness",
        brand="Orbit",
        rating=4.7,
        stock=27,
        images=[product_image("photo-1599901860904-17e6ed7083a0"), product_image("photo-1575052814086-f385e2e2ad1b")],
        colors=["Teal", "Charcoal"],
        sizes=[],
        tags=["fitness", "yoga", "gift"],
        created_at=datetime.now(timezone.utc) - timedelta(days=4),
    ),
]


def make_product(
    product_id: str,
    name: str,
    description: str,
    price: str,
    category: str,
    brand: str,
    rating: float,
    stock: int,
    images: list[str],
    colors: list[str],
    sizes: list[str],
    tags: list[str],
    days_old: int,
) -> Product:
    return Product(
        id=product_id,
        name=name,
        description=description,
        price=Decimal(price),
        category=category,
        brand=brand,
        rating=rating,
        stock=stock,
        images=[product_image(image) for image in images],
        colors=colors,
        sizes=sizes,
        tags=tags,
        created_at=datetime.now(timezone.utc) - timedelta(days=days_old),
    )


PRODUCTS.extend(
    [
        make_product(
            "auralux-mini-speaker",
            "Auralux Mini Bluetooth Speaker",
            "Pocket speaker with waterproof build, punchy bass, and party pairing for patio or travel sound.",
            "44.00",
            "Electronics",
            "Auralux",
            4.4,
            52,
            ["photo-1608043152269-423dbba4e7e1", "photo-1545454675-3531b543be5d"],
            ["Coral", "Black", "Blue"],
            [],
            ["speaker", "portable", "under 50", "travel"],
            14,
        ),
        make_product(
            "northstar-4k-webcam",
            "Northstar 4K Creator Webcam",
            "Sharp 4K webcam with smart framing, low-light correction, and clear dual microphones.",
            "129.00",
            "Electronics",
            "Northstar",
            4.6,
            34,
            ["photo-1587825140708-dfaf72ae4b04", "photo-1618384887929-16ec33fab9ef"],
            ["Black"],
            [],
            ["webcam", "creator", "work", "streaming"],
            9,
        ),
        make_product(
            "nova-mechanical-keyboard",
            "Nova Tactile Mechanical Keyboard",
            "Compact hot-swappable keyboard with quiet tactile switches, RGB profiles, and Mac/Windows layouts.",
            "118.00",
            "Electronics",
            "Nova",
            4.7,
            22,
            ["photo-1587829741301-dc798b83add3", "photo-1618384887929-16ec33fab9ef"],
            ["Charcoal", "Cloud"],
            ["75%", "TKL"],
            ["keyboard", "desk", "gaming", "work"],
            18,
        ),
        make_product(
            "pixelcraft-gaming-monitor",
            "PixelCraft 27-Inch Gaming Monitor",
            "Fast 165Hz QHD display with adaptive sync, low input lag, and rich color for gaming or editing.",
            "289.00",
            "Gaming",
            "PixelCraft",
            4.8,
            15,
            ["photo-1593640408182-31c70c8268f5", "photo-1616588589676-62b3bd4ff6d2"],
            ["Black"],
            ["27 inch"],
            ["gaming", "monitor", "video editing", "creator"],
            6,
        ),
        make_product(
            "pixelcraft-controller-pro",
            "PixelCraft Controller Pro",
            "Wireless controller with remappable paddles, textured grip, and 30-hour rechargeable battery.",
            "69.00",
            "Gaming",
            "PixelCraft",
            4.5,
            48,
            ["photo-1605901309584-818e25960a8f", "photo-1592840496694-26d035b52b48"],
            ["Black", "White", "Blue"],
            [],
            ["gaming", "controller", "gift"],
            11,
        ),
        make_product(
            "kanso-stretch-chino",
            "Kanso Stretch Chino",
            "Polished everyday chino with four-way stretch, tapered fit, and wrinkle resistance.",
            "86.00",
            "Style",
            "Kanso",
            4.4,
            39,
            ["photo-1473966968600-fa801b869a1a", "photo-1515886657613-9f3515b0c78f"],
            ["Khaki", "Navy", "Olive"],
            ["30", "32", "34", "36"],
            ["pants", "work", "travel"],
            25,
        ),
        make_product(
            "vela-cloud-knit-tee",
            "Vela Cloud Knit Tee",
            "Ultra-soft breathable tee cut for layering, workouts, and warm-weather weekends.",
            "28.00",
            "Style",
            "Vela",
            4.3,
            64,
            ["photo-1521572163474-6864f9cf17ab", "photo-1503341504253-dff4815485f1"],
            ["White", "Clay", "Black"],
            ["XS", "S", "M", "L", "XL"],
            ["shirt", "under 50", "basics"],
            13,
        ),
        make_product(
            "vela-commute-jacket",
            "Vela Weatherproof Commute Jacket",
            "Lightweight rain-ready jacket with breathable lining, secure pockets, and reflective trim.",
            "138.00",
            "Style",
            "Vela",
            4.6,
            17,
            ["photo-1543076447-215ad9ba6923", "photo-1506629905607-d9c297d746f7"],
            ["Navy", "Stone"],
            ["S", "M", "L", "XL"],
            ["jacket", "travel", "rain"],
            7,
        ),
        make_product(
            "terra-oak-side-table",
            "Terra Oak Side Table",
            "Compact oak side table with rounded edges, hidden drawer, and apartment-friendly footprint.",
            "159.00",
            "Home",
            "Terra",
            4.5,
            20,
            ["photo-1499933374294-4584851497cc", "photo-1532372320572-cda25653a694"],
            ["Oak", "Walnut"],
            [],
            ["furniture", "living room", "home"],
            30,
        ),
        make_product(
            "luma-cotton-sheet-set",
            "Luma Organic Cotton Sheet Set",
            "Crisp breathable sheets made from organic cotton with deep pockets and hotel-style finish.",
            "96.00",
            "Home",
            "Luma",
            4.7,
            44,
            ["photo-1615873968403-89e068629265", "photo-1505693416388-ac5ce068fe85"],
            ["White", "Sage", "Sky"],
            ["Twin", "Queen", "King"],
            ["bedding", "gift", "home"],
            21,
        ),
        make_product(
            "luma-air-purifier",
            "Luma Room Air Purifier",
            "Quiet HEPA purifier for bedrooms and offices with auto mode, washable prefilter, and air quality ring.",
            "179.00",
            "Home",
            "Luma",
            4.6,
            26,
            ["photo-1600566753190-17f0baa2a6c3", "photo-1556228720-195a672e8a03"],
            ["White"],
            ["Small", "Large"],
            ["air purifier", "home", "wellness"],
            5,
        ),
        make_product(
            "terra-cold-brew-maker",
            "Terra Cold Brew Maker",
            "Glass cold brew pitcher with stainless filter, fridge-friendly profile, and smooth concentrate extraction.",
            "35.00",
            "Kitchen",
            "Terra",
            4.4,
            57,
            ["photo-1461023058943-07fcbe16d735", "photo-1509042239860-f550ce710b93"],
            ["Clear"],
            [],
            ["coffee", "kitchen", "under 50", "gift"],
            12,
        ),
        make_product(
            "terra-chef-knife",
            "Terra 8-Inch Chef Knife",
            "Balanced everyday chef knife with full tang, durable edge, and comfortable pakkawood handle.",
            "74.00",
            "Kitchen",
            "Terra",
            4.8,
            33,
            ["photo-1593618998160-e34014e67546", "photo-1593618998160-e34014e67546"],
            ["Steel"],
            [],
            ["knife", "kitchen", "cooking"],
            19,
        ),
        make_product(
            "orbit-adjustable-dumbbells",
            "Orbit Adjustable Dumbbells",
            "Space-saving dumbbell pair with quick weight changes from 5 to 50 pounds for home strength training.",
            "249.00",
            "Wellness",
            "Orbit",
            4.7,
            12,
            ["photo-1583454110551-21f2fa2afe61", "photo-1517836357463-d25dfeac3438"],
            ["Black"],
            ["5-50 lb"],
            ["fitness", "strength", "home gym"],
            8,
        ),
        make_product(
            "orbit-recovery-massager",
            "Orbit Recovery Massage Tool",
            "Quiet percussion massager with heat mode, six attachments, and guided recovery routines.",
            "119.00",
            "Wellness",
            "Orbit",
            4.5,
            29,
            ["photo-1600881333168-2ef49b341f30", "photo-1518310383802-640c2de311b2"],
            ["Black", "Teal"],
            [],
            ["recovery", "fitness", "gift"],
            16,
        ),
        make_product(
            "northstar-tablet-air",
            "Northstar Tablet Air",
            "Thin tablet with bright display, pencil support, and enough power for notes, sketching, and streaming.",
            "429.00",
            "Mobile",
            "Northstar",
            4.6,
            23,
            ["photo-1544244015-0df4b3ffc6b0", "photo-1561154464-82e9adf32764"],
            ["Silver", "Blue"],
            ["128GB", "256GB"],
            ["tablet", "mobile", "student", "gift"],
            4,
        ),
        make_product(
            "nova-power-bank-20k",
            "Nova 20K Fast Power Bank",
            "Slim high-capacity battery pack with USB-C fast charging, MagSafe-style pad, and display.",
            "58.00",
            "Mobile",
            "Nova",
            4.5,
            61,
            ["photo-1609592806596-4d8b5f898411", "photo-1612815154858-60aa4c59eaa6"],
            ["Black", "White"],
            [],
            ["charger", "travel", "mobile"],
            15,
        ),
        make_product(
            "nova-phone-tripod",
            "Nova Creator Phone Tripod",
            "Foldable tripod with Bluetooth shutter, phone clamp, and tabletop-to-standing height range.",
            "32.00",
            "Mobile",
            "Nova",
            4.2,
            72,
            ["photo-1516035069371-29a1b244cc32", "photo-1502920917128-1aa500764cbd"],
            ["Black"],
            [],
            ["creator", "phone", "under 50", "video"],
            23,
        ),
        make_product(
            "flora-glow-serum",
            "Flora Glow Vitamin C Serum",
            "Lightweight brightening serum with vitamin C, niacinamide, and a non-sticky daily finish.",
            "34.00",
            "Beauty",
            "Flora",
            4.6,
            80,
            ["photo-1620916566398-39f1143ab7be", "photo-1612817288484-6f916006741a"],
            ["Amber"],
            ["30 ml"],
            ["beauty", "skincare", "under 50", "gift"],
            10,
        ),
        make_product(
            "flora-hydration-set",
            "Flora Hydration Skincare Set",
            "Gift-ready cleanser, moisturizer, and overnight mask for balanced hydration and soft skin.",
            "68.00",
            "Beauty",
            "Flora",
            4.7,
            42,
            ["photo-1596462502278-27bfdc403348", "photo-1608248597279-f99d160bfcbc"],
            ["Set"],
            [],
            ["beauty", "mom", "gift", "skincare"],
            3,
        ),
        make_product(
            "trailwise-insulated-bottle",
            "Trailwise Insulated Bottle",
            "Leakproof stainless bottle that keeps drinks cold for 30 hours and fits car cup holders.",
            "31.00",
            "Outdoors",
            "Trailwise",
            4.8,
            88,
            ["photo-1602143407151-7111542de6e8", "photo-1523362628745-0c100150b504"],
            ["Teal", "Black", "Lilac"],
            ["24 oz", "32 oz"],
            ["outdoors", "under 50", "travel", "gift"],
            2,
        ),
        make_product(
            "trailwise-daypack-22",
            "Trailwise 22L Daypack",
            "Light hiking daypack with ventilated straps, hydration sleeve, and weather-resistant pockets.",
            "79.00",
            "Outdoors",
            "Trailwise",
            4.5,
            28,
            ["photo-1553062407-98eeb64c6a62", "photo-1500530855697-b586d89ba3ee"],
            ["Forest", "Black", "Clay"],
            ["22L"],
            ["outdoors", "hiking", "travel", "bag"],
            24,
        ),
        make_product(
            "trailwise-camp-lantern",
            "Trailwise Rechargeable Camp Lantern",
            "Bright rechargeable lantern with dimmer, USB backup power, and magnetic hanging base.",
            "46.00",
            "Outdoors",
            "Trailwise",
            4.4,
            50,
            ["photo-1478827387698-1527781a4887", "photo-1504280390367-361c6d9f38f4"],
            ["Black"],
            [],
            ["camping", "outdoors", "under 50"],
            27,
        ),
        make_product(
            "littleloom-baby-monitor",
            "LittleLoom Smart Baby Monitor",
            "Secure video baby monitor with night vision, room temperature alerts, and parent app controls.",
            "159.00",
            "Baby",
            "LittleLoom",
            4.6,
            18,
            ["photo-1519689680058-324335c77eba", "photo-1546015720-b8b30df5aa27"],
            ["White"],
            [],
            ["baby", "monitor", "gift"],
            29,
        ),
        make_product(
            "littleloom-organic-swaddle",
            "LittleLoom Organic Swaddle Pack",
            "Soft breathable cotton muslin swaddles in a three-pack for newborn naps and stroller shade.",
            "29.00",
            "Baby",
            "LittleLoom",
            4.7,
            73,
            ["photo-1522771930-78848d9293e8", "photo-1515488042361-ee00e0ddd4e4"],
            ["Sage", "Cream"],
            ["3 pack"],
            ["baby", "under 50", "gift"],
            18,
        ),
    ]
)


REVIEWS: list[Review] = [
    Review(id=1, product_id="auralux-pro-headphones", user_id="maya", rating=5, content="The noise canceling is excellent on flights and calls sound clean.", sentiment_score=0.92, created_at=datetime.now(timezone.utc)),
    Review(id=2, product_id="auralux-pro-headphones", user_id="dev", rating=4, content="Great sound and battery, but the case is a little bulky.", sentiment_score=0.72, created_at=datetime.now(timezone.utc)),
    Review(id=3, product_id="northstar-video-laptop", user_id="sam", rating=5, content="Exports 4K timelines quickly and the display is gorgeous.", sentiment_score=0.95, created_at=datetime.now(timezone.utc)),
    Review(id=4, product_id="vela-red-runner", user_id="ana", rating=4, content="Very light and fun color. Runs a half size small.", sentiment_score=0.66, created_at=datetime.now(timezone.utc)),
]


next_review_id = len(REVIEWS) + 1
review_templates = [
    (5, "Exactly what I expected. It feels well made and was easy to start using.", 0.9),
    (4, "Good value for the price. I would like one more color or size option.", 0.72),
]
reviewed_product_ids = {review.product_id for review in REVIEWS}
for product in PRODUCTS:
    if product.id in reviewed_product_ids:
        continue
    for index, (rating, content, sentiment) in enumerate(review_templates):
        REVIEWS.append(
            Review(
                id=next_review_id,
                product_id=product.id,
                user_id=f"shopper-{index + 1}",
                rating=rating,
                content=content,
                sentiment_score=sentiment,
                created_at=datetime.now(timezone.utc) - timedelta(days=index + 1),
            )
        )
        next_review_id += 1
